services:
  inventory-management-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory_management_system
    restart: always
    volumes:
      - .:/inventory_management_system/
    environment:
      FLASK_APP: app/__init__.py  # Point to your Flask app file
      FLASK_ENV: production
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0 --port=8000"
    ports:
      - "9050:8000"
    container_name: inventory-management-web
    stdin_open: true
    tty: true
